services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8010:8010
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/server.go
    networks:
      - elpis_network

networks:
  elpis_network:
    external: true
